### ISSUE TITLE
Wat is dit?

### ISSUE THREAD

**Issue by krijnhoetmer** [zombie0youssra/the-web-is-for-everyone-interactive-functionality#3]
Wat doet een button zonder `<form>`?

https://github.com/zombie0youssra/the-web-is-for-everyone-interactive-functionality/blob/274c61156bce89c93ab5a32b262ca90ede1dc6db/views/overzichtspagina.ejs#L9-L12

**Comment by zombie0youssra** [comment]
hebt het gefixt was me ontglipt
