### ISSUE TITLE
Waarom is dit hele element niet klikbaar?

### ISSUE THREAD

**Issue by krijnhoetmer** [zombie0youssra/the-web-is-for-everyone-interactive-functionality#6]
https://github.com/zombie0youssra/the-web-is-for-everyone-interactive-functionality/blob/274c61156bce89c93ab5a32b262ca90ede1dc6db/views/overzichtspagina.ejs#L24-L29

**Comment by zombie0youssra** [comment]
alleen de title wil ik klikbaar maar ik ga hem duidelijk maken met meer styling en indicator mabey
