### ISSUE TITLE
Titel zit boven plaatje

### ISSUE THREAD

**Issue by moonlightlizaa** [zombie0youssra/the-web-is-for-everyone-interactive-functionality#8]
De titels van de tekenmethodes staan boven de afbeeldingen, dit zorgt een beetje voor verwarring

**Comment by moonlightlizaa** [comment]
<img width="1612" alt="Screenshot 2023-03-31 at 10 36 23 AM" src="https://user-images.githubusercontent.com/106411511/229069801-6637e139-ed75-4390-83be-c11a69761cc3.png">

**Comment by zombie0youssra** [comment]
titel zit nu onder
